export enum BubbleTeaTheme {
    BoardBackground = '#b9b8f5',
    Text = '#585e72',
    NormalSquare = '#FFEBCE',
    DoubleWordSquare = '#f39fd1',
    DoubleLetterSquare = '#accad1',
    TripleWordSquare = '#e685cd',
    TripleLetterSquare = '#7683b8',
    EaselBorder = '#000000',
    Letter = '#ffb198',
    LetterNotItsTurn = '#BBBECA',
    PlacedJoker = '#ff774c',
    LetterBoarderPlaced = '#98ffb1',
    LetterBoarderexchange = '#f1ff83',
    PlacementCursor = '#98ffb1',
    ArrowCursorBackground = '#b198ff',
    ArrowCursorBorder = '#98ffb1',
}
