export enum DarkTheme {
    BoardBackground = '#101216',
    Text = '#000000',
    NormalSquare = '#FFEBCE',
    DoubleWordSquare = '#FFC7C7',
    DoubleLetterSquare = '#BBBECA',
    TripleWordSquare = '#E8A1A1',
    TripleLetterSquare = '#A8BBFF',
    EaselBorder = '#FFFFFF',
    Letter = '#ECBA8C',
    LetterNotItsTurn = '#BBBECA',
    PlacedJoker = '#FB861A',
    LetterBoarderPlaced = '#FF0000',
    LetterBoarderexchange = '#008000',
    PlacementCursor = '#6e8b3d',
    ArrowCursorBackground = '#E8A1A1',
    ArrowCursorBorder = '#FF0000',
}
